### ISSUE TITLE
Blurred Overlay on BlackBerry 

### ISSUE THREAD

**Issue by forbesg** [mcasimir/mobile-angular-ui#235] opened 2015-03-16 12:53 UTC
After displaying the overlay on a BlackBerry 10 device and pressing close, the screen remains blurred.

It is possible to still navigate however the whole screen is blurred and unreadable. 

Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.1.2243 Mobile Safari/537.35+

**Comment by pavelkouril** [comment] 2015-03-17 09:27
Duplicate of #152

**Closed** 2019-01-16 21:15 UTC
